// <auto-generated />
using System;
using FindFamiliar.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FindFamiliar.Server.Migrations
{
    [DbContext(typeof(FamiliarDbContext))]
    [Migration("20260804222955_ConversationalWorkIntake")]
    partial class ConversationalWorkIntake
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("FindFamiliar.Server.Domain.AgentSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClaimExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClaimId")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClaimedByWorkerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClaimedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContextRevisionRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalSessionReference")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClaimedByWorkerId");

                    b.HasIndex("Status", "ClaimExpiresUtc");

                    b.HasIndex("TaskId", "StartedUtc");

                    b.ToTable("AgentSessions", (string)null);
                });

            modelBuilder.Entity("FindFamiliar.Server.Domain.ContextEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(12000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupersedesContextEntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceSessionId");

                    b.HasIndex("SupersedesContextEntryId");

                    b.HasIndex("TaskId");

                    b.HasIndex("ProjectId", "TaskId", "State", "CreatedUtc");

                    b.ToTable("ContextEntries", (string)null);
                });

            modelBuilder.Entity("FindFamiliar.Server.Domain.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ApprovedSessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ApprovedTaskId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedSessionId")
                        .IsUnique()
                        .HasFilter("\"ApprovedSessionId\" IS NOT NULL");

                    b.HasIndex("ApprovedTaskId")
                        .IsUnique()
                        .HasFilter("\"ApprovedTaskId\" IS NOT NULL");

                    b.HasIndex("Status", "UpdatedUtc");

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("FindFamiliar.Server.Domain.ConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "Sequence")
                        .IsUnique();

                    b.ToTable("ConversationMessages", (string)null);
                });

            modelBuilder.Entity("FindFamiliar.Server.Domain.FamiliarProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContextRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("FindFamiliar.Server.Domain.FamiliarTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedOutcome")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Status");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("FindFamiliar.Server.Domain.WorkProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConcurrencyToken")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedSessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedTaskId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ObservedContextRevision")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedOutcome")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId")
                        .IsUnique();

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status", "ConcurrencyToken");

                    b.ToTable("WorkProposals", (string)null);
                });

            modelBuilder.Entity("FindFamiliar.Server.Domain.Worker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Capabilities")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastClaimUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastHeartbeatUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkerKey")
                        .IsUnique();

                    b.ToTable("Workers", (string)null);
                });

            modelBuilder.Entity("FindFamiliar.Server.Domain.AgentSession", b =>
                {
                    b.HasOne("FindFamiliar.Server.Domain.Worker", "ClaimedByWorker")
                        .WithMany("ClaimedSessions")
                        .HasForeignKey("ClaimedByWorkerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FindFamiliar.Server.Domain.FamiliarTask", "Task")
                        .WithMany("AgentSessions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClaimedByWorker");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("FindFamiliar.Server.Domain.ContextEntry", b =>
                {
                    b.HasOne("FindFamiliar.Server.Domain.FamiliarProject", "Project")
                        .WithMany("ContextEntries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FindFamiliar.Server.Domain.AgentSession", "SourceSession")
                        .WithMany("ContextEntries")
                        .HasForeignKey("SourceSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FindFamiliar.Server.Domain.ContextEntry", "SupersedesContextEntry")
                        .WithMany()
                        .HasForeignKey("SupersedesContextEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FindFamiliar.Server.Domain.FamiliarTask", "Task")
                        .WithMany("ContextEntries")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Project");

                    b.Navigation("SourceSession");

                    b.Navigation("SupersedesContextEntry");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("FindFamiliar.Server.Domain.Conversation", b =>
                {
                    b.HasOne("FindFamiliar.Server.Domain.AgentSession", "ApprovedSession")
                        .WithMany()
                        .HasForeignKey("ApprovedSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FindFamiliar.Server.Domain.FamiliarTask", "ApprovedTask")
                        .WithMany()
                        .HasForeignKey("ApprovedTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApprovedSession");

                    b.Navigation("ApprovedTask");
                });

            modelBuilder.Entity("FindFamiliar.Server.Domain.ConversationMessage", b =>
                {
                    b.HasOne("FindFamiliar.Server.Domain.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("FindFamiliar.Server.Domain.FamiliarTask", b =>
                {
                    b.HasOne("FindFamiliar.Server.Domain.FamiliarProject", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FindFamiliar.Server.Domain.WorkProposal", b =>
                {
                    b.HasOne("FindFamiliar.Server.Domain.Conversation", "Conversation")
                        .WithOne("Proposal")
                        .HasForeignKey("FindFamiliar.Server.Domain.WorkProposal", "ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FindFamiliar.Server.Domain.FamiliarProject", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Conversation");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FindFamiliar.Server.Domain.AgentSession", b =>
                {
                    b.Navigation("ContextEntries");
                });

            modelBuilder.Entity("FindFamiliar.Server.Domain.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("FindFamiliar.Server.Domain.FamiliarProject", b =>
                {
                    b.Navigation("ContextEntries");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("FindFamiliar.Server.Domain.FamiliarTask", b =>
                {
                    b.Navigation("AgentSessions");

                    b.Navigation("ContextEntries");
                });

            modelBuilder.Entity("FindFamiliar.Server.Domain.Worker", b =>
                {
                    b.Navigation("ClaimedSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
