// <auto-generated />
using System;
using FindFamiliar.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FindFamiliar.Server.Migrations
{
    [DbContext(typeof(FamiliarDbContext))]
    partial class FamiliarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("FindFamiliar.Server.Domain.AgentSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContextRevisionRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalSessionReference")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "StartedUtc");

                    b.ToTable("AgentSessions", (string)null);
                });

            modelBuilder.Entity("FindFamiliar.Server.Domain.ContextEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(12000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupersedesContextEntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceSessionId");

                    b.HasIndex("SupersedesContextEntryId");

                    b.HasIndex("TaskId");

                    b.HasIndex("ProjectId", "TaskId", "State", "CreatedUtc");

                    b.ToTable("ContextEntries", (string)null);
                });

            modelBuilder.Entity("FindFamiliar.Server.Domain.FamiliarProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContextRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("FindFamiliar.Server.Domain.FamiliarTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedOutcome")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Status");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("FindFamiliar.Server.Domain.AgentSession", b =>
                {
                    b.HasOne("FindFamiliar.Server.Domain.FamiliarTask", "Task")
                        .WithMany("AgentSessions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("FindFamiliar.Server.Domain.ContextEntry", b =>
                {
                    b.HasOne("FindFamiliar.Server.Domain.FamiliarProject", "Project")
                        .WithMany("ContextEntries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FindFamiliar.Server.Domain.AgentSession", "SourceSession")
                        .WithMany("ContextEntries")
                        .HasForeignKey("SourceSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FindFamiliar.Server.Domain.ContextEntry", "SupersedesContextEntry")
                        .WithMany()
                        .HasForeignKey("SupersedesContextEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FindFamiliar.Server.Domain.FamiliarTask", "Task")
                        .WithMany("ContextEntries")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Project");

                    b.Navigation("SourceSession");

                    b.Navigation("SupersedesContextEntry");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("FindFamiliar.Server.Domain.FamiliarTask", b =>
                {
                    b.HasOne("FindFamiliar.Server.Domain.FamiliarProject", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FindFamiliar.Server.Domain.AgentSession", b =>
                {
                    b.Navigation("ContextEntries");
                });

            modelBuilder.Entity("FindFamiliar.Server.Domain.FamiliarProject", b =>
                {
                    b.Navigation("ContextEntries");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("FindFamiliar.Server.Domain.FamiliarTask", b =>
                {
                    b.Navigation("AgentSessions");

                    b.Navigation("ContextEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
