namespace FindFamiliar.Server.Domain;

/// <summary>
/// Server-composed provenance for a Familiar message: what persisted row an answer was drawn from.
///
/// Evidence rows are generated by this application, not by a provider. A provider may cite an id; the
/// application accepts it only if that id was present in the snapshot it sent, and composes
/// <see cref="Label"/> itself from persisted data. An invented id is dropped without comment, because
/// a hallucinated citation is not an event worth reporting to a user.
///
/// <see cref="ReferenceId"/> is a typed identifier, deliberately with no foreign key. Four nullable
/// FK columns — one per possible <see cref="FamiliarEvidenceKind"/> — would encode the same fact four
/// ways and still need a check constraint to say exactly one is set. The real guarantee is that the
/// id came from the snapshot that produced the message, and no foreign key can express that.
/// </summary>
public sealed class FamiliarEvidence
{
    public const int MaxLabelLength = 200;

    public Guid Id { get; set; }

    public Guid MessageId { get; set; }

    public FamiliarMessage Message { get; set; } = null!;

    public FamiliarEvidenceKind Kind { get; set; }

    /// <summary>The referenced row's id, validated against the originating snapshot, not by the schema.</summary>
    public Guid ReferenceId { get; set; }

    /// <summary>Display text composed by the server from persisted data, never model prose.</summary>
    public string Label { get; set; } = string.Empty;
}
